### ISSUE TITLE
Cannot change tab length to 2

### ISSUE THREAD

**Issue by miftahafina** [jawee/language-blade#58] opened 2016-09-26 09:31 UTC
Hello, I'm using language-blade 0.26.2 with atom 1.10.2.

I have problem when I want to change the value of Tab Length to 2, it will always back to 4 automatically. How to fix it?

<img src="http://i.giphy.com/XqdGY1CgMu3wA.gif">

**Comment by Ingramz** [comment] 2016-09-26 10:17
Duplicate of #47

**Closed by Ingramz** 2016-09-26 10:17 UTC
Labels: duplicate
