### ISSUE TITLE
Enable `{!! ... !!}` For Raw Output

### ISSUE THREAD

**Issue by mikebronner** [jawee/language-blade#38] opened 2016-03-27 23:31 UTC
The `{!! ... !!}` raw output tags don't seem to work the same way as the `{{ ... }}` when invoked. Not quite sure why, still investigating.

**Comment by Ingramz** [comment] 2016-03-28 04:51
Their behavior should be identical. If it only happens in a specific file, you can try stripping away any code that precedes it.

**Comment by mikebronner** [comment] 2016-03-28 23:38
It's possibly a conflict with another plugin, something I need to investigate more. The behavior I'm seeing is that when I type the opening `{!!` I only get a closing `}`, instead of ` !!}`.

**Comment by Ingramz** [comment] 2016-03-29 07:35
If you type `{`, the [bracket-matcher](https://github.com/atom/bracket-matcher) package will type in `}` for you.

Fortunately there seems to be a [feature request](https://github.com/atom/bracket-matcher/issues/182) there already to customize bracket behavior per language. That feature request might need a little expansion if you wanted `{` to be completed to `{!! | !!}`.

**Comment by Ingramz** [comment] 2017-06-10 08:56
I'm gonna close this as the issue is too vague. I'll reopen if we can get some sort of intended behavior described here.

**Closed by Ingramz** 2017-06-10 08:56 UTC
Labels: atom-core, enhancement
